
import Navigation from '@/component/Navigation'
import "./globals.css"



export const metadata = {
  title: 'Primer proyecto Next js ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body className="body d-flex flex-column">
        <Navigation />
        <div className='container p-4'>{children}</div>
      </body>
    </html>
  )
}
